package com.example.hello.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Domain model representing a person document persisted in MongoDB.
 * <p>
 * It stores the generated identifier along with the person's first and last name.
 */
@Document(collection = "person")
public class Person {
    @Id
    private String id;
    private String firstName;
    private String lastName;

    /**
     * No-args constructor required by the persistence framework.
     */
    public Person() {}

    /**
     * Creates a new person instance with the provided names.
     *
     * @param firstName given first name; must not be null or blank
     * @param lastName  given last name; must not be null or blank
     */
    public Person(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Returns the unique identifier generated by MongoDB.
     *
     * @return the identifier string
     */
    public String getId() { return id; }

    /**
     * Returns the person's first name.
     *
     * @return first name
     */
    public String getFirstName() { return firstName; }

    /**
     * Returns the person's last name.
     *
     * @return last name
     */
    public String getLastName() { return lastName; }

    /**
     * Sets the identifier. Typically assigned by the database.
     *
     * @param id identifier value
     */
    public void setId(String id) { this.id = id; }

    /**
     * Sets the first name.
     *
     * @param firstName first name value
     */
    public void setFirstName(String firstName) { this.firstName = firstName; }

    /**
     * Sets the last name.
     *
     * @param lastName last name value
     */
    public void setLastName(String lastName) { this.lastName = lastName; }
}
